<?php

namespace MakeEbook;

require_once dirname(__FILE__) . '/../../../lib/app/FileMaker.class.php';

/**
 * Test class for FileMaker.
 * Generated by PHPUnit on 2011-05-19 at 16:14:55.
 */
class FileMakerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FileMaker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FileMaker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testSetHtml().
     */
    public function testSetHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakeHtml().
     */
    public function testMakeHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMakePdf().
     */
    public function testMakePdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
