<?php

namespace MakeEbook;

require_once dirname(__FILE__) . '/../../../lib/app/getUrls.class.php';

/**
 * Test class for getUrls.
 * Generated by PHPUnit on 2011-06-07 at 17:25:49.
 */
class getUrlsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var getUrls
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        try {
            $this->obj = new \MakeEbook\getUrls('http://progit.org/book/');
            $this->obj->removeTags('div', 'buy-book-toc');
            $this->obj->setMenu('ul', 'id', 'toc');
        }
        catch (\Exception $e) {
            $this->fail('Fail to init getUrlsTest');
        }

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testGetUrls() {
        try {
            $this->assertEquals(70, count($this->obj->getUrls()));
        }
        catch (\Exception $e) {
            $this->fail('Error in getUrlsTest');
        }
    }
}

?>
