<?php

namespace MakeEbook;

require_once dirname(__FILE__) . '/../makeEbook.class.php';

/**
 * Test class for makeEbook.
 * Generated by PHPUnit on 2011-05-19 at 10:45:57.
 */
class makeEbookTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var makeEbook
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new makeEbook;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
