<?php

namespace MakeEbook;

require_once dirname(__FILE__) . '/../../../lib/app/Parser.class.php';

/**
 * Test class for Parser.
 * Generated by PHPUnit on 2011-05-19 at 16:14:54.
 */
class ParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Parser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Parser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testParserHTML().
     */
    public function testParserHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetHTML().
     */
    public function testGetHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParserCSS().
     */
    public function testParserCSS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
